language: node_js
os:
  - linux
node_js:
  - 'stable'
sudo: true
env:
  - CXX=g++-4.9
before_install:
  - sudo apt-get -qq update
  - "echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections"
  - "echo ttf-mscorefonts-installer msttcorefonts/present-mscorefonts-eula note | sudo debconf-set-selections"
  - sudo apt-get install ttf-mscorefonts-installer
  - sudo apt-get install g++-4.9
  - sudo apt-get install libcairo2-dev libpango1.0-dev libssl-dev libjpeg62-dev libgif-dev
script:
  - npm run lint
  - gulp minify
  - gulp test
