language: node_js
node_js:
  - "4"
sudo: false
env:
  - CXX=g++-4.9
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - libcairo2-dev
      - libpango1.0-dev
      - libssl-dev
      - libjpeg62-dev
      - libgif-dev
script:
  - npm run lint
  - gulp minify
  - gulp test:browser
  - gulp test:node
